---
# tasks file for php
- name: Install php extensions
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php7.0-gd
    - php7.0-curl
    - php7.0-cli
    - php7.0-cgi
    - php7.0-json
    - php7.0-cgi
    - php7.0-common
    - php-ssh2

- name: checking whether cgi.fix_pathinfo value is 1
  command: awk '/^;cgi.fix_pathinfo=1$/' /etc/php/7.0/fpm/php.ini
  register: check_cgi_fixpath

- name: securing php processor by fixing cgi.fix_pathinfo
  lineinfile:
    dest=/etc/php/7.0/fpm/php.ini
    regexp="^;cgi.fix_pathinfo=1$"
    state=present
    line="cgi.fix_pathinfo=0"
  when: check_cgi_fixpath.stdout | match(";cgi.fix_pathinfo=1")
  notify:
    - restart_php_fpm
  become: yes
